# Generated by Django 4.2.3 on 2023-08-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('ticker', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('insider_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('trade_type', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('form4_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insider_trading',
            },
        ),
    ]
